package Server;

public enum PayloadType {
	CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, SHOOT, CREATE_ROOM, JOIN_ROOM,
	GET_ROOMS, SYNC_GAME_SIZE, ID_CARD, START, GAME_STATE, TIME, TEAM, X_POS, YPOS, R_ANG
}