package Server;

public enum PayloadType {
	CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, SHOOT, TEAM, X_POS, Y_POS, R_ANG,
	CREATE_ROOM, JOIN_ROOM, GET_ROOMS, SYNC_GAME_SIZE, ID_CARD
}