package Server;

public enum PayloadType {
	CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, CREATE_ROOM, JOIN_ROOM, GET_ROOMS,
	SYNC_GAME_SIZE, TEAM, X_POS, YPOS, R_ANG, ID_CARD, START, GAME_STATE, TIME, SHOOT, WALLS, SET_GHOST, SET_HP
}